# Generated by Django 3.2.22 on 2023-10-31 20:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_name', models.CharField(max_length=70)),
                ('consumer_phone', models.CharField(max_length=11)),
                ('consumer_info', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storage_address', models.CharField(max_length=120)),
                ('storage_phone', models.CharField(blank=True, max_length=11)),
                ('storage_info', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_info', models.TextField(blank=True, max_length=250)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymain.consumer')),
                ('storage', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='mymain.storage')),
            ],
        ),
        migrations.CreateModel(
            name='Material_in',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_count', models.PositiveIntegerField(default=1)),
                ('material_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymain.material')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mymain.order')),
            ],
        ),
    ]
